//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace madoka.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("madoka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Temporarily installed fonts are... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxInstallLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxInstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Will be used in the application that will be launched after. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxInstallNoActionLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxInstallNoActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Used in running applications. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxInstallRequireActionLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxInstallRequireActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Release notification is... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxUninstallLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxUninstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not notify to running applications. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxUninstallNoActionLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxUninstallNoActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify to running applications. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_GroupBoxUninstallRequireActionLabel {
            get {
                return ResourceManager.GetString("FontInstallationDialog_GroupBoxUninstallRequireActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary installing now...... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_MessageInstall {
            get {
                return ResourceManager.GetString("FontInstallationDialog_MessageInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending Font installation change event now... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_MessageNotify {
            get {
                return ResourceManager.GetString("FontInstallationDialog_MessageNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Releasing Temporary install fonts now...... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_MessageUninstall {
            get {
                return ResourceManager.GetString("FontInstallationDialog_MessageUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invoke font operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FontInstallationDialog_Title {
            get {
                return ResourceManager.GetString("FontInstallationDialog_Title", resourceCulture);
            }
        }
    }
}
